[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.black]
target-version = ["py38"]

[tool.isort]
profile = "black"
py_version = 38
python = "^3.8"

[tool.poetry.group.classification.dependencies]
librosa = "^0.10.1"
notebook = "^7.0.4"
scipy = "^1.09"
seaborn = "^0.12.2"
sounddevice = "^0.4.6"
soundfile = "^0.12.1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.0.4"

[tool.poetry.group.leaderboard.dependencies]
click = "^8.1.3"
eventlet = "^0.33.3"
flask = "^2.2.2"
flask-apscheduler = "^1.12.4"
flask-limiter = "^3.3.0"
flask-restx = "^1.0.6"
flask-socketio = "^5.3.2"
flask-swagger = "^0.2.14"
flask-swagger-ui = "^4.11.1"
flask-wtf = "^1.1.1"
gevent-websocket = "^0.10.1"
markdown = "^3.4.1"
pydantic = "^1.10.5"
pydub = "^0.25.1"
python-dotenv = "^0.21.1"
requests = "^2.28.2"

[tool.ruff]
ignore = [
  "E501"
]
target-version = "py38"
